### ISSUE TITLE
lens-certificate-info ver3.0.0 is incompatible with 5.5.4-latest.2.220609.2

### ISSUE THREAD

**Issue by khaniqshahid** [jkroepke/lens-extension-certificate-info#3]
lens-certificate-info ver3.0.0 & 3.0.1 both are incompatible with 5.5.4-latest.2.220609.2
![image](https://user-images.githubusercontent.com/22872346/184692902-33b1a2e4-e26b-4402-a8e2-e9b95abbae47.png)

**Comment by jkroepke** [comment]
Yes. Lens 6 is required for version 3. But there are no new features between version 2 and 3, expect the lens version compability.
