### ISSUE TITLE
Doesn't work witj lens 6

### ISSUE THREAD

**Issue by vitalyu** [jkroepke/lens-extension-certificate-info#4]
apple silicone (m1 pro)

```
Lens: 2024.1.300751-latest
Extension API: 6.10.33
Electron: 27.2.4
Chrome: 118.0.5993.159
Node: 18.17.1
```

**Comment by jkroepke** [comment]
Since Lens is closed source, I'm not able to test the extension anymore.

Sorry.

**Comment by rdxmb** [comment]
That's a great pity! I loved to see the cert info in lens!

@jkroepke If there is no chance to update that, could you please add a notification to the README.md or archive the project?  However, I'd love to see the continued ... :(

**Comment by jkroepke** [comment]
Its still working for OpenLens

**Comment by rdxmb** [comment]
I see :+1:
